(source gnu)
(source melpa)
(source melpa-stable)

(depends-on "atom-dark-theme")
(depends-on "atom-one-dark-theme")
(depends-on "auctex")
(depends-on "auto-complete")
(depends-on "helm")
(depends-on "jedi")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popup")
(depends-on "py-autopep8")
(depends-on "pydoc-info")
(depends-on "scss-mode")
